version: "3.8"
services:
    project:
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "24101:24101"
        volumes:
            - ./:/app
        depends_on:
            - lead-php-fpm

    lead-php-fpm:
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            PHP_IDE_CONFIG: serverName=project
        volumes:
            - ./:/app

    lead-php-cli:
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        volumes:
            - ./:/app
